#!/bin/bash

echo "initializing in progress...."

echo "Copying .env.example .env in progress...."
cp .env.example .env
echo "Copying .env.example .env Done"

echo "Installing the app using docker composer image in progress...."
docker run --rm -it -v "$PWD":/app -u "$(id -u)" composer install
echo "Installing Done"

echo "running laravel sail, docker containers going to be built it may take sometime...."
./vendor/bin/sail up -d
echo "running laravel sail Done"

echo "running migrations and run full test case seeder in progress...."
./vendor/bin/sail artisan init:app
echo "running migrations and run full test case seeder Done"

